### ISSUE TITLE
Test the built result?

### ISSUE THREAD

**Issue by timdream** [mozilla/emojione-colr#3]
How do you design a test script for the resulting font? The only thing I could think of currently would be:

1. Fire up Firefox in an automatic faction (via SlimerJS)
2. Load a test web page that would load the built font as web font
3. Go through the code points, paint each of the glyth on a `<canvas>`
4. Ensure they look differently than the system default (implies EmojiOne is encoded on the right code point and is rendered correctly)

I am not sure about (4) is a worthy assertion to set this up -- or if what we could improve from there.

**Comment by jfkthame** [comment]
In principle, the "correct" thing to test would be to paint each supported character on a <canvas> using the web font, and then compare the rendering to the original SVG image. (It won't be pixel-perfect, in general, for a number of reasons, but should be close enough that we can verify it with a "fuzzy match" of some kind.)

Another thing that might be useful would be to generate a test page that simply renders the glyphs from the converted font and the original SVGs side-by-side in a long table, for visual comparison.

**Comment by timdream** [comment]
The browser JS has no access to rendered SVG, only chrome JS has that access. I will work on a visual comparison & a if-render-differently-than-system-emoji test script first.

**Comment by timdream** [comment]
> The browser JS has no access to rendered SVG, only chrome JS has that access.

This is wrong. `ctx.drawImage()` should be able to take a same origin `img` with an `svg` source, although I have not successfully make it work for some reason...

**Comment by jfkthame** [comment]
Hmm. I think we're up against another issue here, too... it seems that Gecko's <canvas> text rendering doesn't support layered-color fonts. (Nor does it support SVG-in-OT glyphs, so that alternative implementation wouldn't help.) 

If I try rendering emoji with Segoe UI Emoji in <canvas>, for example, I just get the B/W glyphs. (And currently, the EmojiOne font created here doesn't include B/W glyphs at all, so it would just render blank.) Similarly, Firefox Emoji renders B/W glyphs only (and its B/W glyphs are not usable as they stand).

Looks like we need to address that in Gecko before a <canvas>-based test will be possible here. And in any case, it's a bug we ought to fix. Though how color-font technologies such as color layers or SVG-in-OT *ought* to interact with <canvas> text features (e.g. fill patterns) may be a question...

**Comment by jfkthame** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1274936 for the Gecko issue.

**Comment by timdream** [comment]
WIP can be found at #6 -- Not sure why GitHub did not reference the two issues.

**Comment by timdream** [comment]
> Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1274936 for the Gecko issue.

Thanks for filing!

**Comment by timdream** [comment]
Fixed by #6 and subsequent commits. Don't over do it!
